# Generated by Django 5.1.2 on 2024-10-16 15:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competidor',
            fields=[
                ('id_competidor', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome_competidor', models.CharField(max_length=255)),
                ('apelidos_competidor', models.CharField(max_length=255)),
                ('peso_competidor', models.CharField(max_length=255)),
                ('vitorias', models.IntegerField()),
                ('derrotas', models.IntegerField()),
                ('empates', models.IntegerField()),
                ('foto_competidor', models.ImageField(blank=True, null=True, upload_to='competidores/')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome_evento', models.CharField(max_length=255)),
                ('lugar_evento', models.CharField(max_length=255)),
                ('data_evento', models.DateField()),
                ('foto_evento', models.ImageField(blank=True, null=True, upload_to='eventos/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fotoperfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil')),
                ('favoritos', models.ManyToManyField(blank=True, related_name='seguidores', to='boxGal.competidor')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='usuario_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuario_permissions_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Combate',
            fields=[
                ('id_combate', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('peso_combate', models.CharField(max_length=255)),
                ('categoria_combate', models.CharField(max_length=255)),
                ('arbitro', models.CharField(max_length=255)),
                ('resultado', models.CharField(max_length=255)),
                ('data_combate', models.DateField()),
                ('boxeador_azul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combates_azul', to='boxGal.competidor')),
                ('boxeador_vermello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combates_vermello', to='boxGal.competidor')),
                ('evento_combate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxGal.evento')),
                ('likes', models.ManyToManyField(blank=True, related_name='combates_gustados', to='boxGal.usuario')),
            ],
        ),
    ]
